GRAPH_MODEL_CP = 0
CIRCUIT_MODEL_CP = 1

BINARY_SEARCH = 0
LINEAR_SEARCH = 1

START_END_SAT = 0
SINGLE_MATRIX_SAT = 1

SEARCH_STRATEGIES = {BINARY_SEARCH:'binary_search', LINEAR_SEARCH:'linear_search'}
